apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  namespace: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms
        image: ajayvarghese2529/bms-app:latest
        ports:
        - containerPort: 80
